name: Start Application Server Action

inputs:
  database_url_encrypted:
    required: true
  gpg_passphrase:
    required: true
  api_key:
    required: true

runs:
  using: composite
  steps:
    - name: Create .env file
      shell: bash
      run: |
        database_url=$(gpg --decrypt --quiet --batch --passphrase "${{ inputs.gpg_passphrase }}" --output - <(echo "${{ inputs.database_url_encrypted }}" | base64 --decode))
        echo "::add-mask::$database_url"
        api_key=${{ inputs.api_key }}
        
        echo -e "DATABASE_URL=$database_url\nAPI_KEY=$api_key" > .env

    - name: Build application
      shell: bash
      run: yarn build

    - name: Wait for application server
      shell: bash
      run: |
        timeout 180 bash -c 'yarn start &
        until curl --silent --head http://127.0.0.1:3000 | grep "200 OK"; do
          echo "Waiting for application server..."
          sleep 5
        done'
