name: Prepare Tests Action

inputs:
  database_url:
    required: true
  api_key:
    required: true

runs:
  using: composite
  steps:
    - name: Create .env file
      shell: bash
      run: |
        DATABASE_URL="${{ inputs.database_url }}"
        API_KEY="${{ inputs.api_key }}"
        
        echo -e "DATABASE_URL=$DATABASE_URL\nAPI_KEY=$API_KEY" > .env

    - name: Build application
      shell: bash
      run: yarn build

    - name: Start application
      shell: bash
      run: |
        timeout 120 bash -c 'yarn start &'
        until curl --silent --head http://localhost:3000 | grep "200 OK"; do
          echo "Waiting for app server..."
          sleep 5
        done