name: Build


on:
  workflow_dispatch:

  push:


env:
  CI: false


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
      
    - name: Check formatting
      run: yarn run prettier

    - name: Run the tests
      run: yarn run test

    - name: Build
      run: yarn run build
