name: Build

on:

  workflow_dispatch:
    
  push:
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Check formatting
      run: npm run prettier

    - name: Run the tests
      run: npm run test

    - name: Build
      run: npm run build
