name: Check Deployment Job

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  check-deployment:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: 'https://sqs-project-weather-check.vercel.app'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: '${{ env.HOSTNAME }}/'

      - name: Run k6 stress test
        uses: grafana/k6-action@v0.3.0
        with:
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
          filename: __tests__/k6/stress-test.js
        env:
          HOSTNAME: ${{ env.HOSTNAME }}
