name: Check Deployment Job

on:
  workflow_dispatch:
    inputs:
      hostname:
        required: true
        type: string
        default: 'https://sqs-project-weather-check.vercel.app'

jobs:
  check-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: '${{ inputs.hostname }}/'

      - name: Run k6 stress test
        uses: grafana/k6-action@v0.3.0
        with:
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
          filename: __tests__/k6/stress-test.js
        env:
          HOSTNAME: ${{ inputs.hostname }}
