name: Create Database Branch Job

on:
  workflow_call:
    outputs:
      database_url:
        value: ${{ jobs.create-database-branch.outputs.database_url }}

jobs:
  create-database-branch:
    runs-on: ubuntu-latest

    outputs:
      database_url: 'mysql://${{ steps.create_database_credentials.outputs.username }}:${{ steps.create_database_credentials.outputs.password }}@${{ steps.create_database_credentials.outputs.hostname }}/sqs-project-weather-check?sslaccept=strict'

    env:
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

    steps:
      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Create database branch
        uses: planetscale/create-branch-action@v1
        id: create_branch
        with:
          org_name: 'niklas-wilhelm'
          database_name: 'sqs-project-weather-check'
          branch_name: '${{ steps.branch-name.outputs.current_branch }}--${{ github.run_id }}'
          from: 'main'

      - name: Create database branch credentials
        uses: planetscale/create-branch-password-action@v1
        id: create_database_credentials
        with:
          org_name: 'niklas-wilhelm'
          database_name: 'sqs-project-weather-check'
          branch_name: '${{ steps.branch-name.outputs.current_branch }}--${{ github.run_id }}'
          name: 'pass-${{ steps.branch-name.outputs.current_branch }}--${{ github.run_id }}'