name: Create Database Branch Job

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

    outputs:
      database_url_encrypted:
        value: ${{ jobs.create-database-branch.outputs.database_url_encrypted }}

jobs:
  create-database-branch:
    runs-on: ubuntu-latest

    outputs:
      database_url_encrypted: ${{ steps.encrypt-database-url.outputs.database_url_encrypted }}

    env:
      PLANETSCALE_BASE_BRANCH: 'main'
      PLANETSCALE_ORG_NAME: 'niklas-wilhelm'
      PLANETSCALE_DB_NAME: 'sqs-project-weather-check'
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Create database branch
        uses: planetscale/create-branch-action@v1
        with:
          org_name: ${{ env.PLANETSCALE_ORG_NAME }}
          database_name: ${{ env.PLANETSCALE_DB_NAME }}
          branch_name: ${{ inputs.branch_name }}
          from: ${{ env.PLANETSCALE_BASE_BRANCH }}

      - name: Create database branch credentials
        uses: planetscale/create-branch-password-action@v3
        id: create-database-credentials
        with:
          org_name: ${{ env.PLANETSCALE_ORG_NAME }}
          database_name: ${{ env.PLANETSCALE_DB_NAME }}
          branch_name: ${{ inputs.branch_name }}
          name: 'pass-${{ inputs.branch_name }}'

      - name: Encrypt database url
        id: encrypt-database-url
        run: |
          database_url="mysql://${{ steps.create-database-credentials.outputs.username }}:${{ steps.create-database-credentials.outputs.password }}@${{ steps.create-database-credentials.outputs.hostname }}/sqs-project-weather-check?sslaccept=strict"
          echo "::add-mask::$database_url"
          database_url_encrypted=$(gpg --symmetric --batch --passphrase "$GPG_PASSPHRASE" --output - <(echo "$database_url") | base64 -w0)
          echo "database_url_encrypted=$database_url_encrypted" >> $GITHUB_OUTPUT
